name: Deploy to Maven Repository

on:
  workflow_call:
    inputs:
      maven-command:
        required: false
        type: string
        default: "--batch-mode deploy"
      java-version:
        required: false
        type: string
        default: "21"
      server-id:
        required: false
        type: string
        default: "central"
      ref:
        required: false
        type: string
        default: "main"
      upload-artifact:
        required: false
        type: boolean
        default: false
      artifact-id:
        default: artifact
        required: false
        type: string

    secrets:
      maven-username:
        required: false
      maven-password:
        required: false

      maven-token:
        required: true
      gpg-private-key:
        required: false
      gpg-passphrase:
        required: false


jobs:
  mvn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref}}
          fetch-depth: 0

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Display settings.xml
        run: cat ~/.m2/settings.xml

      - name: Sign and Deploy jar to Maven Central
        run: mvn ${{ inputs.maven-command }}
        env:
          MAVEN_USERNAME: ${{ secrets.maven-username }}

      - name: Upload all Maven target directories
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-id }}
          path: '**/target'
